// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(

    apiKey: 'AIzaSyCZFx9IOEZmAc708BNXCd0IKD1WICEqXMM',
    appId: '1:602649121057:web:61d7396dd2bb6174f6ee60',
    messagingSenderId: '602649121057',
    projectId: 'areisto-space',
    authDomain: 'areisto-space.firebaseapp.com',
    storageBucket: 'areisto-space.firebasestorage.app',
    measurementId: 'G-3J2FHJZZ9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd_0LFiz0s3bRfz5G8qkavtT_4tF_k8o4',
    appId: '1:602649121057:android:507deab522b0dc58f6ee60',
    messagingSenderId: '602649121057',
    projectId: 'areisto-space',
    storageBucket: 'areisto-space.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbJOopiiWnxWchTshQb9kaIeuwkb81MbE',
    appId: '1:602649121057:ios:590e1a1ddfe0bce3f6ee60',
    messagingSenderId: '602649121057',
    projectId: 'areisto-space',
    storageBucket: 'areisto-space.firebasestorage.app',
    iosBundleId: 'com.aristospace.gaza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbJOopiiWnxWchTshQb9kaIeuwkb81MbE',
    appId: '1:602649121057:ios:590e1a1ddfe0bce3f6ee60',
    messagingSenderId: '602649121057',
    projectId: 'areisto-space',
    storageBucket: 'areisto-space.firebasestorage.app',
    iosBundleId: 'com.aristospace.gaza',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZFx9IOEZmAc708BNXCd0IKD1WICEqXMM',
    appId: '1:602649121057:web:aa2d435cfe1b420df6ee60',
    messagingSenderId: '602649121057',
    projectId: 'areisto-space',
    authDomain: 'areisto-space.firebaseapp.com',
    storageBucket: 'areisto-space.firebasestorage.app',
    measurementId: 'G-1NLGBB0WTH',
  );
}
